export const ADD_INGREDIENTS_REQUEST: 'ADD_INGREDIENTS_REQUEST' = 'ADD_INGREDIENTS_REQUEST';
export const ADD_INGREDIENTS_SUCCESS: 'ADD_INGREDIENTS_SUCCESS' = 'ADD_INGREDIENTS_SUCCESS';
export const ADD_INGREDIENTS_ERROR: 'ADD_INGREDIENTS_ERROR' = 'ADD_INGREDIENTS_ERROR';

export const SELECT_INGREDIENT: 'SELECT_INGREDIENT' = 'SELECT_INGREDIENT';
export const SET_CURRENT_ITEM: 'SET_CURRENT_ITEM' = 'SET_CURRENT_ITEM';

export const SET_ORDER_DETAIL_REQUEST: 'SET_ORDER_DETAIL_REQUEST' = 'SET_ORDER_DETAIL_REQUEST';
export const SET_ORDER_DETAIL_SUCCESS: 'SET_ORDER_DETAIL_SUCCESS' = 'SET_ORDER_DETAIL_SUCCESS';
export const SET_ORDER_DETAIL_ERROR: 'SET_ORDER_DETAIL_ERROR' = 'SET_ORDER_DETAIL_ERROR';

export const UPDATE_CONSTRUCTOR_LIST: 'UPDATE_CONSTRUCTOR_LIST' = 'UPDATE_CONSTRUCTOR_LIST';

export const REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST' = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS' = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR: 'REGISTER_USER_ERROR' = 'REGISTER_USER_ERROR';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_ERROR: 'LOGIN_ERROR' = 'LOGIN_ERROR';

export const CHECK_AUTH_SESSION: 'CHECK_AUTH_SESSION' = 'CHECK_AUTH_SESSION';

export const LOGOUT: 'LOGOUT' = 'LOGOUT';

export const GET_USER: 'GET_USER' = 'GET_USER';

export const UPDATE_USER: 'UPDATE_USER' = 'UPDATE_USER';
