export const ADD_INGREDIENTS_REQUEST = 'ADD_INGREDIENTS_REQUEST';
export const ADD_INGREDIENTS_SUCCESS = 'ADD_INGREDIENTS_SUCCESS';
export const ADD_INGREDIENTS_ERROR = 'ADD_INGREDIENTS_ERROR';

export const SELECT_INGREDIENT = 'SELECT_INGREDIENT';
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';

export const SET_ORDER_DETAIL_REQUEST = 'SET_ORDER_DETAIL_REQUEST';
export const SET_ORDER_DETAIL_SUCCESS = 'SET_ORDER_DETAIL_SUCCESS';
export const SET_ORDER_DETAIL_ERROR = 'SET_ORDER_DETAIL_ERROR';

export const UPDATE_CONSTRUCTOR_LIST = 'UPDATE_CONSTRUCTOR_LIST';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CHECK_AUTH_SESSION = 'CHECK_AUTH_SESSION';
export const LOGOUT = 'LOGOUT';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const ORDERS_CONNECT = 'ORDERS_CONNECT';
export const ORDERS_DISCONNECT = 'ORDERS_DISCONNECT';
export const ORDERS_WS_CONNECTING = 'ORDERS_WS_CONNECTING';
export const ORDERS_WS_OPEN = 'ORDERS_WS_OPEN';
export const ORDERS_WS_CLOSE = 'ORDERS_WS_CLOSE';
export const ORDERS_WS_MESSAGE = 'ORDERS_WS_MESSAGE';
export const ORDERS_WS_ERROR = 'ORDERS_WS_ERROR';

export const PROFILE_ORDERS_CONNECT = 'PROFILE_ORDERS_CONNECT';
export const PROFILE_ORDERS_DISCONNECT = 'PROFILE_ORDERS_DISCONNECT';
export const PROFILE_ORDERS_WS_CONNECTING = 'ORDERS_WS_ERROR';
export const PROFILE_ORDERS_WS_OPEN = 'PROFILE_ORDERS_WS_OPEN';
export const PROFILE_ORDERS_WS_CLOSE = 'PROFILE_ORDERS_WS_CLOSE';
export const PROFILE_ORDERS_WS_ERROR = 'PROFILE_ORDERS_WS_ERROR';
export const PROFILE_ORDERS_WS_MESSAGE = 'PROFILE_ORDERS_WS_MESSAGE';
